---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: semver:~0.32
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nginx-ingress
    version: 1.40.3
  values:
    controller:
      kind: DaemonSet
      service:
        externalIPs:
          - 161.92.170.142
          - 161.92.169.152
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
    tcp:
      50000: "default/jenkins-agent:50000"
